# To install in conda: conda env create -f environment.yml
# To activate: conda activate dsa_playground
# to remove: conda env remove -n dsa_playground

name: &env_name dsa_playground
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - black=20.8b1
  - pyaml-env=1.1.0
  - pandas=1.1.5
  - jupyterlab=3.0.6
  - jupyter_contrib_nbextensions=0.5.1
  - nb_conda_kernels=2.3.1
  - rise=5.7.1
  - plotly=4.14.3
  - statsmodels=0.12.1
  - scikit-learn=0.24.1
  - xgboost=1.3.3

